name: tour
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  argon_buttons_flutter: ^1.1.0
  ionicons: ^0.1.2
  fluentui_icons: ^1.0.0

  #image
  flutter_svg: ^1.0.3
  image_picker: ^0.8.5+3
  uuid: ^3.0.6
  cached_network_image: ^3.2.0

  #location
  location: ^4.3.0
  geocoding: ^2.0.4

  #backend
  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.15
  firebase_storage: ^10.2.16
  dio: ^4.0.6

  #functional_programming
  dartz: ^0.10.1

  #state_management
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.6+1
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.7
  build_runner: ^2.1.11

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/json/
      #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
