// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNN3Htu9JsF78plQAQphPy9KnmSyRPqJA',
    appId: '1:62548435445:web:a655401d04cd5c235f80bc',
    messagingSenderId: '62548435445',
    projectId: 'tour-dbbd4',
    authDomain: 'tour-dbbd4.firebaseapp.com',
    storageBucket: 'tour-dbbd4.appspot.com',
    measurementId: 'G-7WGSE2B0CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0L3AtSwIu7EwchANR3EnzRa_UDHAMjpE',
    appId: '1:62548435445:android:f986beed52f1ba625f80bc',
    messagingSenderId: '62548435445',
    projectId: 'tour-dbbd4',
    storageBucket: 'tour-dbbd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBru_zALb1P0SL1DrpA34TUPBTNL5kLA6c',
    appId: '1:62548435445:ios:a4016e453b0c7c1a5f80bc',
    messagingSenderId: '62548435445',
    projectId: 'tour-dbbd4',
    storageBucket: 'tour-dbbd4.appspot.com',
    iosClientId:
        '62548435445-pbh1nv5a79gueok72220f6ssabejooef.apps.googleusercontent.com',
    iosBundleId: 'com.example.tour',
  );
}
